/image_raw:
  durability: volatile
  history: keep_last
  depth: 1000
  reliability: reliable

# /image_raw:
#   durability: volatile
#   history: keep_all
#   reliability: reliable

/livox/lidar:
  durability: volatile
  history: keep_all
  reliability: reliable

/livox/imu:
  durability: volatile
  history: keep_all
  reliability: reliable